<?xml version="1.0" encoding="UTF-8" ?>
<testsuites errors="2"
            failures="1"
            tests="1">

  <testsuite name="signin-test"
    errors="2" failures="1" hostname="" id="" package="signin-test" skipped="0"
    tests="1" time="8.070" timestamp="Mon, 28 Mar 2016 05:40:11 GMT">
  
    <testcase name="Checking for login redirect" time="8.070" assertions="3">

    

      <failure message="Testing if element &lt;#test&gt; contains text: &quot;test&quot;. Element could not be located.">    at Object.module.exports.Checking for login redirect (/Users/ashleystanbridge/Desktop/W o r k  S p a c e/projects/tightrope/test/integration/signin-test.js:11:15)
    at Module.call (/Users/ashleystanbridge/Desktop/W o r k  S p a c e/projects/tightrope/node_modules/nightwatch/lib/runner/module.js:63:34)
    at /Users/ashleystanbridge/Desktop/W o r k  S p a c e/projects/tightrope/node_modules/nightwatch/lib/runner/testcase.js:97:29
    at _fulfilled (/Users/ashleystanbridge/Desktop/W o r k  S p a c e/projects/tightrope/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/Users/ashleystanbridge/Desktop/W o r k  S p a c e/projects/tightrope/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/Users/ashleystanbridge/Desktop/W o r k  S p a c e/projects/tightrope/node_modules/q/q.js:796:13)
    at /Users/ashleystanbridge/Desktop/W o r k  S p a c e/projects/tightrope/node_modules/q/q.js:556:49
    at runSingle (/Users/ashleystanbridge/Desktop/W o r k  S p a c e/projects/tightrope/node_modules/q/q.js:137:13)
    at flush (/Users/ashleystanbridge/Desktop/W o r k  S p a c e/projects/tightrope/node_modules/q/q.js:125:13)
    at _combinedTickCallback (node.js:370:9)</failure>

    
    </testcase>
  
  
  </testsuite>
</testsuites>
